// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ovander/parashift/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// StoreExceptionRepository is an autogenerated mock type for the StoreExceptionRepository type
type StoreExceptionRepository struct {
	mock.Mock
}

type StoreExceptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *StoreExceptionRepository) EXPECT() *StoreExceptionRepository_Expecter {
	return &StoreExceptionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, e
func (_m *StoreExceptionRepository) Create(ctx context.Context, e *model.StoreException) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.StoreException) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreExceptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type StoreExceptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - e *model.StoreException
func (_e *StoreExceptionRepository_Expecter) Create(ctx interface{}, e interface{}) *StoreExceptionRepository_Create_Call {
	return &StoreExceptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, e)}
}

func (_c *StoreExceptionRepository_Create_Call) Run(run func(ctx context.Context, e *model.StoreException)) *StoreExceptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.StoreException))
	})
	return _c
}

func (_c *StoreExceptionRepository_Create_Call) Return(_a0 error) *StoreExceptionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StoreExceptionRepository_Create_Call) RunAndReturn(run func(context.Context, *model.StoreException) error) *StoreExceptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, tenantID, id
func (_m *StoreExceptionRepository) Delete(ctx context.Context, tenantID uuid.UUID, id uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreExceptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type StoreExceptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - id uuid.UUID
func (_e *StoreExceptionRepository_Expecter) Delete(ctx interface{}, tenantID interface{}, id interface{}) *StoreExceptionRepository_Delete_Call {
	return &StoreExceptionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, tenantID, id)}
}

func (_c *StoreExceptionRepository_Delete_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, id uuid.UUID)) *StoreExceptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *StoreExceptionRepository_Delete_Call) Return(_a0 error) *StoreExceptionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StoreExceptionRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *StoreExceptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ListByDateRange provides a mock function with given fields: ctx, tenantID, from, to
func (_m *StoreExceptionRepository) ListByDateRange(ctx context.Context, tenantID uuid.UUID, from time.Time, to time.Time) ([]*model.StoreException, error) {
	ret := _m.Called(ctx, tenantID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListByDateRange")
	}

	var r0 []*model.StoreException
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) ([]*model.StoreException, error)); ok {
		return rf(ctx, tenantID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) []*model.StoreException); ok {
		r0 = rf(ctx, tenantID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.StoreException)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, tenantID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreExceptionRepository_ListByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByDateRange'
type StoreExceptionRepository_ListByDateRange_Call struct {
	*mock.Call
}

// ListByDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *StoreExceptionRepository_Expecter) ListByDateRange(ctx interface{}, tenantID interface{}, from interface{}, to interface{}) *StoreExceptionRepository_ListByDateRange_Call {
	return &StoreExceptionRepository_ListByDateRange_Call{Call: _e.mock.On("ListByDateRange", ctx, tenantID, from, to)}
}

func (_c *StoreExceptionRepository_ListByDateRange_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, from time.Time, to time.Time)) *StoreExceptionRepository_ListByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *StoreExceptionRepository_ListByDateRange_Call) Return(_a0 []*model.StoreException, _a1 error) *StoreExceptionRepository_ListByDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StoreExceptionRepository_ListByDateRange_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) ([]*model.StoreException, error)) *StoreExceptionRepository_ListByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewStoreExceptionRepository creates a new instance of StoreExceptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreExceptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreExceptionRepository {
	mock := &StoreExceptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
